CFLAGS=-Wall -pedantic -std=c++11

tables: 
	g++ -o tables $(CFLAGS) $(BFLAG) main.cpp users.cpp users.h sessions.cpp sessions.h products.h products.cpp fileshelp.h fileshelp.cpp mergedTable.h mergedTable.cpp

clear:
	rm tables
